services:
  # POSTGRES
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: lg-manutencao
      POSTGRES_PASSWORD: lg-manutencao
      POSTGRES_DB: lg_manut_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lg-manutencao -d lg_manut_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data:
    driver: local
